# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

SOURCES = main.cpp
TEMPLATE = app
TARGET = QTEST
RESOURCES += Resource.qrc
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(QTEST.pri)
win32:RC_FILE = QTEST.rc
